"""add users table and user_id on games

Revision ID: 5e4ef35397ab
Revises: b641c65ce8a2
Create Date: 2026-07-22 20:56:06.400231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e4ef35397ab'
down_revision: Union[str, Sequence[str], None] = 'b641c65ce8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: user_id is added NOT NULL with no backfill. Pre-auth games had no
    # owner, so this migration assumes the games table is empty (true for this
    # pre-release app). If a future migration must add a NOT NULL FK to a
    # populated table, add the column nullable, backfill, then tighten it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apple_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('displayName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_apple_sub'), ['apple_sub'], unique=True)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_index(batch_op.f('ix_games_user_id'), ['user_id'], unique=False)
        # SQLite batch mode requires a named constraint.
        batch_op.create_foreign_key(
            'fk_games_user_id_users', 'users', ['user_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_games_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_apple_sub'))

    op.drop_table('users')
    # ### end Alembic commands ###
